Setup debugging environement
+ Updated sbs
+ Setup framebuffer
+ Setup Serial port for debugging
+ Setup useful bochs functions for debugging
+ Added the libc sub project

diff --git a/sbs b/sbs
--- a/sbs
+++ b/sbs
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-source .sbs/sbscfg.bash
-
 QEMU=${QEMU:-"qemu-system-x86_64"}
 BOCHS=${BOCHS:-"bochs"}
 
@@ -13,38 +11,66 @@ MODE=${3:-"debug"}
 PROJECT_DIR=${PROJECT_DIR:-$PWD}
 PROJECT_FILE=${PROJECT_FILE:-"${PROJECT_DIR}/sbs.project"}
 
-KERNEL_FILE="build/${ARCH}/${MODE}/kernel.${ARCH}.elf"
+KERNEL_FILE="build/${MODE}/kernel.${ARCH}.elf"
 
 NOT_VERB=(remove_update_files)
 
+source ".sbs/verbs_builtins.bash"
+
 help() {
-    echo "
+    echo "\
 Usage: sbs <verb=help> <arch=i686-pc> <mode=debug>
 Verbs:
-    help     : show this menu
-    build    : build the kernel
-    clean    : clean object files
-    iso      : generate the iso file
-    run-qemu : boots the iso file with qemu
-    run-bochs: boots the iso file with bochs
-    all      : equivalent to build->iso
-    all-bochs: equivalent to all->run-bochs
-    all-qemu : equivalent to all->run-qemu
+    help    (default): show this menu
+    build            : build the kernel
+    clean            : clean object files
+    iso              : generate the iso file
+    run-qemu         : boots the iso file with qemu
+    run-bochs        : boots the iso file with bochs
+    all              : equivalent to build->iso
+    all-bochs        : equivalent to all->run-bochs
+    all-qemu         : equivalent to all->run-qemu
+    all-qemu-no-grub : build the kernel and boot with qemu directly
 Arch:
-    i686-pc: for i686-pc platforms
+    i686-pc (default): for i686-pc platform
 Modes:
-    debug
-    release
+    debug   (default): for debug   builds
+    release          : for release builds\
 "
 }
 
-build() {
-    echo "ARCH=${ARCH}" > ".sbs/sbsrc"
-    source .sbs/sbs.bash
+clean() {
+    echo "Cleaning objects and temporary files"
+    if [[ -f ${PROJECT_FILE} ]]; then
+        source ${PROJECT_FILE}
+    else
+        echo "Project file not found!"
+        exit 1
+    fi
+    BUILD_DIR=${BUILD_DIR:-"${PROJECT_DIR}/build/"}
+    _RBDIR=${_RBDIR:-"${BUILD_DIR}/"}
+    [[ -d "${_RBDIR}/" ]] && rm -rf "${_RBDIR}/"
+    [[ -d ".sbs/tmp" ]] && rm -rf ".sbs/tmp"
+    [[ -f "isodir/boot/helium.elf" ]] && rm -rf "isodir/boot/helium.elf"
+    [[ -f "run/bx_enh_dbg.ini" ]] && rm -rf "run/bx_enh_dbg.ini"
+    [[ -f "run/helium.iso" ]] && rm -rf "run/helium.iso"
+    [[ -f "run/bochslog.txt" ]] && rm -rf "run/bochslog.txt"
+    echo "Cleaned!"
 }
 
 iso() {
     if [[ -f ${KERNEL_FILE} ]]; then
+        if [[ ! $(command -v grub-file) ]]; then
+            echo "Please install grub before generating the iso"
+        fi
+        echo $PWD
+        grub-file --is-x86-multiboot ${KERNEL_FILE}
+        if [[ $? -ne 0 ]]; then
+            echo "Kernel file is not multiboot compliant"
+            exit 1
+        else
+            echo "Kernel file is multiboot compliant"
+        fi
         cp ${KERNEL_FILE} isodir/boot/helium.elf
         mkdir -p run/
         grub-mkrescue isodir -o run/helium.iso
@@ -73,86 +99,17 @@ run-qemu() {
 run-bochs() {
     cd run
     if [[ -f helium.iso ]]; then
-        ${BOCHS} -f bochsrc.txt -q
+        ${BOCHS} -f bochs.cfg -rc bochsrc -q
         exit $?
     else
         echo "helium.iso file not found, try generating it first with 'sbs iso'"  
     fi
 }
 
-clean() {
-    echo "Cleaning build files..."
-    if [[ -f ${PROJECT_FILE} ]]; then
-        source ${PROJECT_FILE}
-    else
-        echo "Project file not found!"
-        exit 1
-    fi
-    BUILD_DIR=${BUILD_DIR:-"${PROJECT_DIR}/build/"}
-    _RBDIR=${_RBDIR:-"${BUILD_DIR}/"}
-    [[ -d "${_RBDIR}/debug/obj" ]] && rm -rf "${_RBDIR}/debug/obj"
-    [[ -d "${_RBDIR}/release/obj" ]] && rm -rf "${_RBDIR}/release/obj"
-    echo "Cleaned build files"
-}
-
-remove_update_files() {
-    echo "Removing temporary file..."
-    if [[ $(basename ${PWD}) = "__update_sbs_tmp" ]]; then
-        cd ..
-    fi
-    rm -rf __update_sbs_tmp
-    if [[ $? -ne 0 ]]; then
-        echo "Problem while trying to delete temporary files!"
-        echo "Try deleting '__update_sbs_tmp' by yourself"
-        exit 1
-    fi
-}
-
-update() {
-    mkdir -p __update_sbs_tmp
-    cd __update_sbs_tmp
-    echo "Downloading update..."
-    
-    if [[ $(command -v wget) ]]; then
-        CMD="wget"
-    elif [[ $(command -v curl) ]]; then
-        CMD="curl"
-    else
-        echo "Please install wget or curl before trying to update"
-        cd ..
-        remove_update_files
-        exit 1
-    fi
-    ${CMD} ${UPDATE_URL}
-    if [[ $? -ne 0 ]]; then
-        echo "Problem while downloading the update files!"
-        remove_update_files
-        exit 1
-    fi
-    echo "Extracting files..."
-    tar -xzf latest.tar.gz
-    if [[ $? -ne 0 ]]; then
-        echo "Problem while extracting the update files!"
-        remove_update_files
-        exit 1
-    fi
-    echo "Copying new files to .sbs directory..."
-    \cp -r ShellBuildSystem-latest/.sbs/* ../.sbs
-    if [[ $? -ne 0 ]]; then
-        echo "Problem while copying the update files!"
-        remove_update_files
-        exit 1
-    fi
-    cd ..
-    remove_update_files
-    echo "Updated sbs!"
-}
-
 all() {
     build
     iso
 }
-
 all-bochs() {
     all
     run-bochs
@@ -161,6 +118,11 @@ all-bochs() {
 all-qemu() {
     all
     run-qemu
+}
+
+all-qemu-no-grub() {
+    build
+    ${QEMU} -kernel build/debug/kernel.i686-pc.elf
 }
 
 if [[ $(command -v ${VERB}) && ! ${NOT_VERB[@]} =~ (^|[[:space:]])"${VERB}"($|[[:space:]]) ]]; then
